---
- name: Install Apache
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name:  Install Apache Package
      package:
        name: "{{ apache_pkg }}"
        state: present
    - name: Copy web content
      copy:
        src: web/
        directory_mode: true
        dest: /var/www/html
...
