---
- name: Manage Apache Deployment
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name:  Install Apache Package
      package:
        name: "{{ apache_pkg }}"
        state: present
    - name: Copy web content
      copy:
        src: web/
        directory_mode: true
        dest: /var/www/html
    - name: Start and Enable Apache Service
      service:
        name: "{{ apache_pkg }}"
        state: started
        enabled: true
    - name: Custom web content
      template:
        src: server.j2
        dest: /var/www/html/server.html
    - name: Firewall Package
      package:
        name: "{{ firewall_pkg }}"
        state: present
    - name: Firewall Service
      service:
        name: "{{ firewall_pkg }}"
        enabled: true
        state: started
    - name: UFW Ubuntu
      ufw:
          state: enabled
          policy: deny
          rule: allow
          port: "{{ item }}"
          proto: tcp
      loop:
        - "80"
        - "22"
      when: ansible_distribution == "Ubuntu"
    - name: Firewalld CentOS
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "http"
        - "ssh"
      when: ansible_distribution == "CentOS"
    - name: Configure Apache
      lineinfile:
        path: "{{ apache_cfg }}"
        line: "ServerName {{ ansible_hostname }}"
        insertafter: "#ServerName"
      notify:
        - restart_apache
    - name: Secure default ACL for apache user on document root
      acl:
        path: /var/www/html
        entity: "{{ apache_user }}"
        etype: user
        state: present
        permissions: rx
        default: true
    - name: Secure default ACL for others on document root
      acl:
        path: /var/www/html
        entry: default:others::---
        state: present
    - name: Set read and execute permissions on deocument root for apache user
      acl:
        path: /var/www/html
        entity: "{{ apache_user }}"
        etype: user
        state: present
        permissions: rx
    - name: Set permissions to others to nothing on document root
      acl:
        path: /var/www/html
        entry: others::---
        state: present
  handlers:
      - name: restart_apache
        service:
          name: "{{ apache_pkg }}"
          state: restarted
...
